version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "cmakelang"
        dependency-type: "production"
      - dependency-name: "sphinx"
        dependency-type: "production"