name: Security Scan

on:
  push:
    branches:
      - main

    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/LICENSE"
      - "**/.*"
      - "**/.vscode/*.json"

  schedule:
    - cron: 0 6 1 * *

env:
  BUILD_TYPE: Release

jobs:
  codeql-security-scan:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [cpp]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt --assume-yes install --no-install-recommends libboost-iostreams-dev
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
