name: Mark stale issues and pull requests

on:
  schedule:
    - cron: 0 1 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v3.0.18
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-pr-stale: 90
          days-before-close: 7
          stale-issue-message: "Issue will be closed soon without new activity."
          stale-pr-message: "Pull request will be closed soon without new activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          close-issue-message: "Issue is automatically closed due to inactivity."
          close-pr-message: "Pull request is automatically closed due to inactivity."
